apiVersion: v1
appVersion: 1.16.0.1226-7eb2c8f6f
description: Plex Media Server
name: kube-plex
version: 0.2.7
keywords:
  - plex
home: https://plex.tv/
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
sources:
  - https://hub.docker.com/r/mauroniewolskicesca/kube-plex-arm64
  - https://hub.docker.com/r/mauroniewolskicesca/pms-docker-arm64/
maintainers:
  - name: mauroniewolskicesca
